name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100

    - name: Install ReportGenerator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool

    - name: Build
      run: dotnet build src/MasDen.Request.Pipeline.sln --configuration Release

    - name: Run Tests
      run: dotnet test src/MasDen.Request.Pipeline.sln --collect:"XPlat Code Coverage" --settings .runsettings

    - name: Code coverage report
      run: ~/.dotnet/tools/reportgenerator -reports:CodeCoverage/**/coverage.cobertura.xml -targetdir:coverlet/reports

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: Coverage reports
        path: coverlet/reports